New device list (#36)
* Attempt at deviceName as primary key

* Remove ID from display list too

* remove original migrations for remake

* Successss

* sv

* asd

* sdg

* Rechecking Import function

* Beautify

* Beautify

* Add validators while importing

* Correct error

* nk

* asd

* Add validationerror function

* vbh

* Year,department and name together considered to be unique

* Revert "Year,department and name together considered to be unique"

This reverts commit 228e9c9c7d7b73b7f74fe9723113e8d502eef224.

* New backup of migrations

Delete Redundant migrations

* Remake migrations to one file

* Add new device tag

* Correction

* Changed attributes

Name -> NOT UNIQUE
deviceTag -> UNIQUE

* Remove New migration too

* Added Device Tag

* Validation when number of devices are less

* Separated valdiation based code out of model file

* Added custom char fields

* Error correction of previous commit e0e6651

AttributeError: module 'django.db.models' has no attribute 'TitleCaseCharField'

* Error correction of commit e0e6651

         super(UpperCaseCharField, self).__init__(*args, **kwargs)
       TypeError: super(type, obj): obj must be an instance or subtype of type

* Change all fields to custom char fields ( Migration)

* Split model into parts

* Split admin into modules

* Change folder name for better access

* Correcting errors

* Error correction

* Correction in error

* Corrections

* Corrections

* Correction for migration error

* Settings modulated

* Better split with comments

* Check

Try to minimize queries

* asdf

* beh