Error correction of commit e0e6651
         super(UpperCaseCharField, self).__init__(*args, **kwargs)
       TypeError: super(type, obj): obj must be an instance or subtype of type